/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

import static org.example.Calculator.makeCalculation;


public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        double firstNumber = scanner.nextDouble();
        double secondNumber = scanner.nextDouble();
        String action = scanner.next();
        if (action.equals("/") && secondNumber == 0) {
            System.out.println("Division by zero");
            return;
        }
        System.out.println(makeCalculation(firstNumber, secondNumber, action));
        System.out.println(Solution.isPalindrome(1223));
    }

}
