/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.example.StringUtils.*;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String s = "Hello world!";
        System.out.println(isPalindrome(s));
        System.out.println(reverse(s));
        System.out.println(countVowels("LinkageErrory"));
    }

    public String getGreeting() {
        return "Hello, SDET";
    }
}
